"""
Client-configurable security recommendations per PII class.
"""

SECURITY_HINTS = {
    "PII.EMAIL": "RESTRICTED_ACCESS",
    "PII.NAME": "RESTRICTED_ACCESS",
    "PII.DOB": "MASK_OR_RESTRICT",
    "PII.PHONE": "RESTRICTED_ACCESS",
    "PII.ADDRESS": "MASK_OR_RESTRICT",
    "PII.NATIONAL_ID": "HIGHLY_RESTRICTED",

    # SENSITIVE
    "SENSITIVE.PASSWORD": "DENY_ALL_EXCEPT_SERVICE",
    "SENSITIVE.TOKEN": "DENY_ALL_EXCEPT_SERVICE",
    "SENSITIVE.FINANCIAL": "RESTRICTED_ACCESS",
    "SENSITIVE.SECURITY": "HIGHLY_RESTRICTED",
}
